language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - "sudo touch /var/log/stripe-mock-server.log"
  - "sudo chown travis /var/log/stripe-mock-server.log"
script: "bundle exec rspec; bundle exec rspec -t live"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44a1f4718ae2efb67eac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
